
const areasOfOperation = ["THROUGHOUT ENGLAND AND WALES", "BRACKNELL FOREST", "AFGHANISTAN", "AFRICA", "THROUGHOUT ENGLAND", "WEST BERKSHIRE", "ALBANIA", "ASIA", "THROUGHOUT WALES", "READING", "ALGERIA", "EUROPE", "THROUGHOUT LONDON", "SLOUGH", "NORTH AMERICA", "WINDSOR AND MAIDENHEAD", "ANDORRA", "SOUTH AMERICA", "WOKINGHAM", "ANGOLA", "OCEANIA", "BARKING AND DAGENHAM", "ANTARCTICA", "BARNET", "BEXLEY", "ANTIGUA AND BARBUDA", "BRENT", "ARGENTINA", "BROMLEY", "ARMENIA", "CAMDEN", "CITY OF LONDON", "AUSTRALIA", "CITY OF WESTMINSTER", "AUSTRIA", "CROYDON", "AZERBAIJAN", "EALING", "ENFIELD", "BAHAMAS", "GREENWICH", "BAHRAIN", "HACKNEY", "BANGLADESH", "HAMMERSMITH AND FULHAM", "GREATER LONDON", "BARBADOS", "HARINGEY", "GREATER MANCHESTER", "BELARUS", "HARROW", "BELGIUM", "HAVERING", "BELIZE", "HILLINGDON", "BENIN", "HOUNSLOW", "ISLINGTON", "BHUTAN", "KENSINGTON AND CHELSEA", "BOLIVIA", "KINGSTON UPON THAMES", "BOSNIA-HERZEGOVINA", "LAMBETH", "BOTSWANA", "LEWISHAM", "BRAZIL", "MERTON", "BRUNEI", "NEWHAM", "BULGARIA", "REDBRIDGE", "MERSEYSIDE", "BURKINA FASO", "RICHMOND UPON THAMES", "BURUNDI", "SOUTHWARK", "CAMBODIA", "SUTTON", "CAMEROON", "TOWER HAMLETS", "CANADA", "WALTHAM FOREST", "CAPE VERDE", "WANDSWORTH", "BOLTON", "CENTRAL AFRICAN REPUBLIC", "BURY", "CHAD", "MANCHESTER CITY", "CHILE", "OLDHAM", "CHINA", "ROCHDALE", "COLOMBIA", "SALFORD CITY", "COMOROS", "STOCKPORT", "REPUBLIC OF CONGO", "TAMESIDE", "TRAFFORD", "SOUTH YORKSHIRE", "COSTA RICA", "WIGAN", "CROATIA", "KNOWSLEY", "CUBA", "LIVERPOOL CITY", "CYPRUS", "SEFTON", "TYNE AND WEAR", "CZECH REPUBLIC", "ST HELENS", "DENMARK", "WIRRAL", "DJIBOUTI", "BARNSLEY", "DOMINICA", "DONCASTER", "DOMINICAN REPUBLIC", "ROTHERHAM", "WEST MIDLANDS", "ECUADOR", "SHEFFIELD CITY", "EGYPT", "GATESHEAD", "WEST YORKSHIRE", "EL SALVADOR", "NEWCASTLE UPON TYNE CITY", "EQUATORIAL GUINEA", "NORTH TYNESIDE", "ERITREA", "SOUTH TYNESIDE", "ESTONIA", "SUNDERLAND", "ETHIOPIA", "BIRMINGHAM CITY", "COVENTRY CITY", "DUDLEY", "FIJI", "SANDWELL", "FINLAND", "SOLIHULL", "FRANCE", "WALSALL", "WOLVERHAMPTON", "BRADFORD CITY", "GABON", "CALDERDALE", "GAMBIA", "KIRKLEES", "LEEDS CITY", "GEORGIA", "CITY OF WAKEFIELD", "GERMANY", "NOTTINGHAM CITY", "GHANA", "GREECE", "GRENADA", "GUATEMALA", "GUINEA", "GUINEA-BISSAU", "GUYANA", "HAITI", "HONDURAS", "HUNGARY", "ICELAND", "INDIA", "INDONESIA", "IRAN", "IRAQ", "ISRAEL", "ITALY", "IVORY COAST", "JAMAICA", "CENTRAL BEDFORDSHIRE", "JAPAN", "BUCKINGHAMSHIRE", "CAMBRIDGESHIRE", "JORDAN", "CHESHIRE EAST", "KAZAKHSTAN", "CORNWALL", "KENYA", "CUMBRIA", "KIRIBATI", "DERBYSHIRE", "KUWAIT", "DEVON", "KYRGYZSTAN", "DORSET", "LAOS", "DURHAM", "LATVIA", "EAST SUSSEX", "LEBANON", "ESSEX", "LESOTHO", "GLOUCESTERSHIRE", "LIBERIA", "HAMPSHIRE", "LIBYA", "HERTFORDSHIRE", "LIECHTENSTEIN", "ISLE OF WIGHT", "LITHUANIA", "KENT", "LUXEMBOURG", "LANCASHIRE", "LEICESTERSHIRE", "MACEDONIA", "LINCOLNSHIRE", "MADAGASCAR", "NORFOLK", "NORTH YORKSHIRE", "MALAWI", "NORTHAMPTONSHIRE", "MALAYSIA", "NORTHUMBERLAND", "MALDIVES", "NOTTINGHAMSHIRE", "MALI", "OXFORDSHIRE", "MALTA", "POWYS", "MARSHALL ISLANDS", "SHROPSHIRE", "SOMERSET", "MAURITANIA", "STAFFORDSHIRE", "MAURITIUS", "SUFFOLK", "SURREY", "MEXICO", "WARWICKSHIRE", "MICRONESIA", "WEST SUSSEX", "MOLDOVA", "WILTSHIRE", "MONACO", "NORTH SOMERSET", "MONGOLIA", "BATH AND NORTH EAST SOMERSET", "SOUTH GLOUCESTERSHIRE", "MOROCCO", "BRISTOL CITY", "MOZAMBIQUE", "HARTLEPOOL", "BURMA", "MIDDLESBROUGH", "NAMIBIA", "REDCAR AND CLEVELAND", "NAURU", "STOCKTON-ON-TEES", "NEPAL", "KINGSTON UPON HULL CITY", "NETHERLANDS", "NORTH LINCOLNSHIRE", "NORTH EAST LINCOLNSHIRE", "EAST RIDING OF YORKSHIRE", "NEW ZEALAND", "CONWY", "NICARAGUA", "ISLE OF ANGLESEY", "NIGER", "BLAENAU GWENT", "NIGERIA", "BRIDGEND", "CAERPHILLY", "NORTH KOREA", "CARDIFF", "CEREDIGION", "NORWAY", "CARMARTHENSHIRE", "OMAN", "DENBIGHSHIRE", "PAKISTAN", "FLINTSHIRE", "PALAU", "MERTHYR TYDFIL", "MONMOUTHSHIRE", "PANAMA", "NEATH PORT TALBOT", "PAPUA NEW GUINEA", "NEWPORT CITY", "PARAGUAY", "PEMBROKESHIRE", "PERU", "PLYMOUTH CITY", "PHILIPPINES", "CITY OF SWANSEA", "POLAND", "VALE OF GLAMORGAN", "PORTUGAL", "THURROCK", "WREXHAM", "QATAR", "HALTON", "REPUBLIC OF IRELAND", "GWYNEDD", "CITY OF YORK", "ROMANIA", "TORFAEN", "RUSSIA", "WARRINGTON", "RWANDA", "RHONDDA CYNON TAFF", "LUTON", "ST KITTS-NEVIS", "MILTON KEYNES", "ST LUCIA", "DERBY CITY", "ST VINCENT AND GRENADINES", "BOURNEMOUTH", "SAMOA", "POOLE", "SAN MARINO", "DARLINGTON", "SAO TOME AND PRINCIPE", "BRIGHTON AND HOVE", "SAUDI ARABIA", "SOUTHAMPTON CITY", "SENEGAL", "PORTSMOUTH CITY", "SEYCHELLES", "LEICESTER CITY", "SIERRA LEONE", "RUTLAND", "SINGAPORE", "STOKE-ON-TRENT CITY", "SLOVAKIA", "SWINDON", "SLOVENIA", "BLACKBURN WITH DARWEN", "SOLOMON ISLANDS", "BLACKPOOL", "SOMALIA", "SOUTHEND-ON-SEA", "SOUTH AFRICA", "TELFORD & WREKIN", "SOUTH KOREA", "PETERBOROUGH CITY", "SPAIN", "HEREFORDSHIRE", "SRI LANKA", "WORCESTERSHIRE", "SUDAN", "MEDWAY", "SURINAM", "ISLES OF SCILLY", "SWAZILAND", "TORBAY", "SWEDEN", "CHESHIRE WEST & CHESTER", "SWITZERLAND", "BEDFORD", "SYRIA", "TAJIKISTAN", "TANZANIA", "THAILAND", "TOGO", "TONGA", "TRINIDAD AND TOBAGO", "TUNISIA", "TURKEY", "TURKMENISTAN", "TUVALU", "UGANDA", "UKRAINE", "UNITED ARAB EMIRATES", "UNITED STATES OF AMERICA", "URUGUAY", "UZBEKISTAN", "VANUATU", "VENEZUELA", "VIETNAM", "YEMEN", "SERBIA", "DEMOCRATIC REPUBLIC OF THE CONGO", "ZAMBIA", "ZIMBABWE", "MONTENEGRO", "SCOTLAND", "NORTHERN IRELAND", "ANTARCTICA", "TIMOR-LESTE", "OCCUPIED PALESTINIAN TERRITORIES", "KOSOVO", "AKROTIRI AND DHEKELIA", "AMERICAN SAMOA", "ANGUILLA", "ARUBA", "BERMUDA", "BRITISH INDIAN OCEAN TERRITORY", "BRITISH VIRGIN ISLANDS", "CAYMAN ISALNDS", "CHRISTMAS ISLAND", "CLIPPERTON ISLAND", "COCOS (KEELING) ISLANDS", "COOK ISLANDS", "EASTERISLAND", "FALKLAND ISLANDS", "FAROE ISLANDS", "FRENCH GUYANA", "FRENCH POLYNESIA", "GIBRALTAR", "GREENLAND", "GUADELOUPE", "GUAM", "GUERNSEY", "HONG KONG", "ISLE OF MAN", "JAN MAYEN", "JERSEY", "JUAN FERNANDEZ ISLANDS", "MACAU", "MARTINIQUE", "MAYOTTE", "MONTSERRAT", "NETHERLANDS ANTILLES", "NEW CALEDONIA", "NIUE", "NORFOLK ISLAND", "NORTHERN MARIANA ISLAND", "PITCAIRN ISLANDS", "PUERTO RICO", "REUNION", "ROSS DEPENDENCY", "ST BARTHELEMY", "ST HELENA", "ST MARTIN", "ST PIERRE AND MIQUELON", "SOUTH GEORGIA", "SVALBARD", "TAIWAN", "TOKELAU", "TURKS AND CAICOS ISLANDS", "U.S. VIRGIN ISLANDS", "WALLIS AND FUTUNA", "REPUBLIC OF SOUTH SUDAN",]

const categories = [
  {
    "id" : 102,
    "name" : "Education/training"
  },
  {
    "id" : 105,
    "name" : "The prevention or relief of poverty"
  },
  {
    "id" : 101,
    "name" : "General charitable purposes"
  },
  {
    "id" : 103,
    "name" : "The advancement of health or saving of lives"
  },
  {
    "id" : 104,
    "name" : "Disability"
  },
  {
    "id" : 108,
    "name" : "Religious activities"
  },
  {
    "id" : 110,
    "name" : "Amateur sport"
  },
  {
    "id" : 109,
    "name" : "Arts/culture/heritage/science"
  },
  {
    "id" : 107,
    "name" : "Accommodation/housing"
  },
  {
    "id" : 113,
    "name" : "Economic/community development/employment"
  },
  {
    "id" : 112,
    "name" : "Environment/conservation/heritage"
  },
  {
    "id" : 115,
    "name" : "Human rights/religious or racial harmony/equality or diversity"
  },
  {
    "id" : 116,
    "name" : "Recreation"
  },
  {
    "id" : 111,
    "name" : "Animals"
  },
  {
    "id" : 117,
    "name" : "Other charitable purposes"
  },
  {
    "id" : 106,
    "name" : "Overseas aid/famine relief"
  },
  {
    "id" : 114,
    "name" : "Armed forces/emergency service efficiency"
  }
]

const beneficiaries = [
  {
    "id" : 201,
    "name" : "Children/young people"
  },
  {
    "id" : 202,
    "name" : "Elderly/old people"
  },
  {
    "id" : 203,
    "name" : "People with disabilities"
  },
  {
    "id" : 205,
    "name" : "Other charities or voluntary bodies"
  },
  {
    "id" : 206,
    "name" : "Other defined groups"
  },
  {
    "id" : 207,
    "name" : "The general public/mankind"
  },
  {
    "id" : 204,
    "name" : "People of a particular ethnic or racial origin"
  }
]

const operations = [
  {
    "id" : 301,
    "name" : "Makes grants to individuals"
  },
  {
    "id" : 302,
    "name" : "Makes grants to organisations"
  },
  {
    "id" : 303,
    "name" : "Provides other finance"
  },
  {
    "id" : 307,
    "name" : "Provides advocacy/advice/information"
  },
  {
    "id" : 308,
    "name" : "Sponsors or undertakes research"
  },
  {
    "id" : 305,
    "name" : "Provides buildings/facilities/open space"
  },
  {
    "id" : 306,
    "name" : "Provides services"
  },
  {
    "id" : 304,
    "name" : "Provides human resources"
  },
  {
    "id" : 309,
    "name" : "Acts as an umbrella or resource body"
  },
  {
    "id" : 310,
    "name" : "Other charitable activities"
  }
]

export { areasOfOperation, categories, beneficiaries, operations }
